### ISSUE TITLE
Error when player join to server

### ISSUE THREAD

**Issue by ms0ur** [zigazajc007/CryptoCurrency#1]
Server Thread: YatopiaMC
git-Yatopia-ver/1.16.5-103 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugin version: 1.0.1
Java 11
I'm use MySQL
Vault is installed
MySQL in other plugins work normal

------------------------------
Current Thread: Server thread
PID: 17 | Suspended: false | Native: false | State: TIMED_WAITING
Suspected Plugins:
CryptoCurrency{enabled,ver=1.0.1,path=plugins/CryptoCurrency-1.0.1.jar}

Stack:
java.base@11.0.9/jdk.internal.misc.Unsafe.park(Native Method)
java.base@11.0.9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
java.base@11.0.9/java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(SynchronousQueue.java:761)
java.base@11.0.9/java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:689)
java.base@11.0.9/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:151)
com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
com.rabbitcompany.utils.MySql.createPlayerWallet(MySql.java:49)
com.rabbitcompany.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:24)
com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor128.execute(Unknown Source)
app//org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
app//org.bukkit.plugin.EventExecutor$$Lambda$4303/0x0000000840f15c40.execute(Unknown Source)
app//co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
app//org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
app//org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611)
app//net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357)
app//net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:304)
app//net.minecraft.server.v1_16_R3.PlayerList$$Lambda$6536/0x0000000841a5d440.run(Unknown Source)
app//net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:317)
app//net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:607)
app//net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:164)
app//net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1608)
app//net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:443)
app//net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1423)
app//net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1144)
app//net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
app//net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3130/0x000000084086ec40.run(Unknown Source)
java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
------------------------------
--- DO NOT REPORT THIS TO YATOPIA - THIS IS NOT A BUG OR A CRASH ---
------------------------------

**Comment by zigazajc007** [comment]
Hello,

Can you please check that you have provided correct mysql data in config.yml file

**Comment by ms0ur** [comment]
The plugin worked fine with MySQL for about 20 minutes, about 20 players were able to log in to the server, but then suddenly, when the next player re-entered, it started to give an error when players entered, and disconnect them from the server. There were no errors before that.

**Comment by ms0ur** [comment]
MySQL config:

mysql: true

mysql_host: "localhost"
mysql_port: "3306"
mysql_database: "btc"
mysql_user: "server"
mysql_password: "password"
mysql_useSSL: false

**Comment by zigazajc007** [comment]
Does your server has enabled or disabled online-mode?

If it has disabled online-mode you need to be careful about players joining with unallowed Minecraft names. That can be solved really easy with a login plugin that has integrated this feature. One of them is plugin called Passky ([https://polymart.org/resource/passky.726](https://polymart.org/resource/passky.726)) which I have also made.

**Comment by ms0ur** [comment]
I use AuthME and it prohibits the use of unallowed names, but I'm willing to upgrade to your authorization plugin if it supports MySQL and BungeeCord. And user dont use a unallowed name.

**Comment by ms0ur** [comment]
I deleted the user from the database, after which the error occurred, and the error disappeared

**Comment by zigazajc007** [comment]
If that happen again can you please provide me the user data before you delete it?
So I will see where the problem might be.

**Comment by ms0ur** [comment]
Ok, thank you for your help and quick response
